language: php

sudo: false

git:
  depth: 3

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - COMPOSER_FLAGS="--prefer-stable --prefer-source" WP_VERSION=latest

php:
  - 5.6
  # - 7.0
  - 7.1
  - nightly

matrix:
  # fast_finish: true
  include:
  #   - php: 5.6
  #     env:
  #       - COMPOSER_FLAGS="--prefer-lowest --prefer-stable --prefer-source"
    - php: 7.0
      env:
        - TEST_VERSION=true
        - COMPOSER_FLAGS="--prefer-stable --prefer-source"
        - WP_VERSION=latest
  allow_failures:
    - php: nightly

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - composer install

install:
  - if [[ $TEST_VERSION == true ]]; then travis_retry composer require satooshi/php-coveralls:dev-master $COMPOSER_FLAGS --no-interaction --no-scripts --no-progress ; fi

script:
  - vendor/bin/phpcs -s --standard=phpcs.ruleset.xml .
  - vendor/bin/phpunit --coverage-clover logs/clover.xml

after_script:
  - if [[ $TEST_VERSION == true ]]; then travis_retry php vendor/bin/coveralls --verbose ; fi
